apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: example-team
  description: The example team responsible for example components
spec:
  type: team
  parent: ops  # Optional: You can specify the parent group if this group is a child of another group
  members:
    - jdoe
    - asmith
    - bjohnson
